---
cog_bundle_version: 4
name: rundeck
description: "go-rundeck interface"
author: "Stephen Price <stephen@stp5.net>"
homepage: "https://github.com/steeef/docker-rundeck-cli"
version: "0.1.4"
docker:
  image: "steeef/cog-rundeck"
  tag: "latest"
commands:
  list:
    executable: "/bundle/list"
    description: "List available jobs."
    long_description: |
      List jobs in a project. If "--prj" is not specified, use the default.
    rules:
      - "when command is rundeck:list allow"
    options:
      prj:
        description: "Project ID of jobs to list."
        type: string
        required: false
        short_flag: p
  run:
    executable: "/bundle/run"
    description: "Run a job by name."
    rules:
      - "when command is rundeck:run allow"
    arguments: "<jobname>"
    options:
      prj:
        description: "Project ID of jobs to list."
        type: string
        required: false
        short_flag: p
      args:
        description: "Arguments to send to the job."
        type: string
        required: false
        short_flag: a
  history:
    executable: "/bundle/history"
    description: "Get job history for a specified project."
    rules:
      - "when command is rundeck:history allow"
    options:
      prj:
        description: "Project ID of jobs to list."
        type: string
        required: false
        short_flag: p
